# Generated by Django 5.1.3 on 2025-01-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=150)),
                ('qualification', models.CharField(max_length=150)),
                ('passout_year', models.CharField(max_length=15)),
                ('source', models.CharField(choices=[('instagram', 'instagram'), ('facebook', 'facebook'), ('referral', 'referral'), ('walkin', 'walkin')], default='walkin', max_length=100)),
                ('course', models.CharField(choices=[('TESTING', 'TESTING'), ('PYTHON DJANGO', 'PYTHON DJANGO'), ('MEARN', 'MEARN'), ('DATA SCIENCE', 'DATA SCIENCE'), ('JAVA SPRING', 'JAVA SPRING'), ('.NET', '.NET')], default='PYTHON DJANGO', max_length=25)),
                ('course_mode', models.CharField(choices=[('ONLINE', 'ONLINE'), ('OFFLINE', 'OFFLINE'), ('HYBRID', 'HYBRID')], default='OFFLINE', max_length=20)),
                ('status', models.CharField(choices=[('FOLLOWUP', 'FOLLOW-UP'), ('PROCEEDTOADMISSION', 'PROCEED-TO-ADMISSION'), ('NOTINTERESETED', 'NOT-INTERESTED')], default='FOLLOWUP', max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
